<div>
    {% if not is_index %}
	    <span>本作品采用</span>
        <a href="https://creativecommons.org/licenses/by/4.0/">知识共享署名 4.0 国际许可协议</a>
        <span>进行许可。 转载时请注明原文链接。</span>
		<img src="/images/wechat.jpg" alt="Do it" style="margin: auto; display: block;" height="200" width="200"/>
        <div style="margin: auto; text-align: center; font-size: 0.8em; color: grey;">备注请声明tceason.github.io</div>
    {% endif %}
</div>

